name: 'Koyeb: cleanup after a deployment'
description: 'Remove a Koyeb service created by koyeb/action-git-deploy'

inputs:
  app-name:
    description: "The Koyeb application to delete"
    required: false

runs:
  using: "composite"
  steps:
    - name: Slugify application name
      shell: sh
      run: |
        if [ -z "${{ inputs.app-name }}" ]; then
          # Remove the owner from the repository
          APP_SLUG=$(echo '${{ github.repository }}/${{ github.event.ref }}' | cut -d '/' -f 2-)
        else
          APP_SLUG="${{ inputs.app-name }}"
        fi

        # sed: to replace non alphanum chars with -
        # tail: limit to the last 23 chars (maximum Koyeb application name)
        # sed: if the leading char is a dash, remove it
        echo "APP_SLUG=$(echo $APP_SLUG | sed 's/[^a-z0-9]/-/g' | tail -c 24 | sed 's/^-//g')" | tee $GITHUB_ENV

    - name: Delete the application
      shell: sh
      run: |
        koyeb app delete ${{ env.APP_SLUG }} || echo "Unable to remove the application, likely because it doesn't exist."