name: 'Koyeb: cleanup after a deployment'
description: 'Remove a Koyeb service created by koyeb/action-git-deploy'

inputs:
  api-token:
    description: "Koyeb API token"
    required: true

  app-name:
    description: "The Koyeb application to delete"
    required: false

runs:
  using: "composite"
  steps:
    - name: Slugify application name
      shell: sh
      run: |
        if [ -z "${{ inputs.app-name }}" ]; then
          echo "APP_SLUG=$(echo '${{ github.repository }}/${{ github.event.ref }}' | cut -d '/' -f 2- | sed 's/\//-/g' | tail -c 24)" | tee $GITHUB_ENV
        else
          echo "APP_SLUG=${{ inputs.app-name }}" | tee $GITHUB_ENV
        fi

    - name: Install and configure the Koyeb CLI
      uses: koyeb-community/install-koyeb-cli@v2
      with:
        api_token: "${{ inputs.api-token }}"

    - name: Delete the application
      shell: sh
      run: |
        koyeb app delete ${{ env.APP_SLUG }} || echo "Unable to remove the application, likely because it doesn't exist."