name: 'Koyeb: cleanup after a deployment'
description: 'Remove a Koyeb service created by koyeb/action-git-deploy'

inputs:
  api-token:
    description: "Koyeb API token"
    required: true

  app-name:
    description: "The Koyeb application name where the service is"
    required: false

  service-name:
    description: "The Koyeb service name to delete"
    required: false
    default: "${{ github.event.ref }}"

runs:
  using: "composite"
  steps:
    - name: Slugify application name
      shell: sh
      run: |
        if [ -z "${{ inputs.app-name }}" ]; then
          echo "APP_SLUG=$(echo '${{ github.repository }}/${{ github.event.ref }}' | cut -d '/' -f 2- | sed 's/\//-/g' | cut -c 1-23)" | tee $GITHUB_ENV
        else
          echo "APP_SLUG=${{ inputs.app-name }}" | tee $GITHUB_ENV
        fi

    - name: Install and configure the Koyeb CLI
      uses: koyeb-community/install-koyeb-cli@v2
      with:
        api_token: "${{ inputs.api-token }}"

    - name: Delete the service
      shell: sh
      run: |
        koyeb service delete ${{ env.APP_SLUG }}/${{ inputs.service-name }} || echo "Unable to remove the service, likely because it doesn't exist."