name: 'Koyeb: manage secrets'
description: 'Create or update a Koyeb secret'

inputs:
  secret-name:
    description: "The Koyeb secret name to create or update"
    required: true

  secret-value:
    description: "The Koyeb secret value to create or update"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create or update the Koyeb secret
      shell: sh
      run: |
        ${{ github.action_path }}/../scripts/secret-upsert.py \
          --secret-name "${{ inputs.secret-name }}" \
          --secret-value "${{ inputs.secret-value }}"